//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetriX.Shared.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RetriX.Shared.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slots Exported Successfully.
        /// </summary>
        internal static string ExportSlotsMessage {
            get {
                return ResourceManager.GetString("ExportSlotsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No slots found!.
        /// </summary>
        internal static string ExportSlotsMessageError {
            get {
                return ResourceManager.GetString("ExportSlotsMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Slots.
        /// </summary>
        internal static string ExportSlotsTitle {
            get {
                return ResourceManager.GetString("ExportSlotsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file supplied is not the expected one. Try a different file..
        /// </summary>
        internal static string FileHashMismatchMessage {
            get {
                return ResourceManager.GetString("FileHashMismatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong file.
        /// </summary>
        internal static string FileHashMismatchTitle {
            get {
                return ResourceManager.GetString("FileHashMismatchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the game.
        ///The game file may be corrupt or in a wrong format: try another one..
        /// </summary>
        internal static string GameLoadingFailAlertMessage {
            get {
                return ResourceManager.GetString("GameLoadingFailAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load game.
        /// </summary>
        internal static string GameLoadingFailAlertTitle {
            get {
                return ResourceManager.GetString("GameLoadingFailAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to reset the game?.
        /// </summary>
        internal static string GamePlayResetMessage {
            get {
                return ResourceManager.GetString("GamePlayResetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Game.
        /// </summary>
        internal static string GamePlayResetTitle {
            get {
                return ResourceManager.GetString("GamePlayResetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to stop?.
        /// </summary>
        internal static string GamePlayStopMessage {
            get {
                return ResourceManager.GetString("GamePlayStopMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Playing.
        /// </summary>
        internal static string GamePlayStopTitle {
            get {
                return ResourceManager.GetString("GamePlayStopTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save current state?.
        /// </summary>
        internal static string GamePlayTemeSaveMessage {
            get {
                return ResourceManager.GetString("GamePlayTemeSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Game.
        /// </summary>
        internal static string GamePlayTempSaveTitle {
            get {
                return ResourceManager.GetString("GamePlayTempSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while running the game.
        ///Restart RetriX and try again..
        /// </summary>
        internal static string GameRunningFailAlertMessage {
            get {
                return ResourceManager.GetString("GameRunningFailAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game runtime error.
        /// </summary>
        internal static string GameRunningFailAlertTitle {
            get {
                return ResourceManager.GetString("GameRunningFailAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slots Imported Successfully.
        /// </summary>
        internal static string ImportSlotsMessage {
            get {
                return ResourceManager.GetString("ImportSlotsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Canceled!.
        /// </summary>
        internal static string ImportSlotsMessageCancel {
            get {
                return ResourceManager.GetString("ImportSlotsMessageCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Slots.
        /// </summary>
        internal static string ImportSlotsTitle {
            get {
                return ResourceManager.GetString("ImportSlotsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will replace the current slots, continue?.
        /// </summary>
        internal static string ImportStatesMessage {
            get {
                return ResourceManager.GetString("ImportStatesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Slots.
        /// </summary>
        internal static string ImportStatesTitle {
            get {
                return ResourceManager.GetString("ImportStatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandai.
        /// </summary>
        internal static string ManufacturerNameBandai {
            get {
                return ResourceManager.GetString("ManufacturerNameBandai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FinalBurn Neo.
        /// </summary>
        internal static string ManufacturerNameFBAlpha {
            get {
                return ResourceManager.GetString("ManufacturerNameFBAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IGS.
        /// </summary>
        internal static string ManufacturerNameIGS {
            get {
                return ResourceManager.GetString("ManufacturerNameIGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEC.
        /// </summary>
        internal static string ManufacturerNameNEC {
            get {
                return ResourceManager.GetString("ManufacturerNameNEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nintendo.
        /// </summary>
        internal static string ManufacturerNameNintendo {
            get {
                return ResourceManager.GetString("ManufacturerNameNintendo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEGA.
        /// </summary>
        internal static string ManufacturerNameSega {
            get {
                return ResourceManager.GetString("ManufacturerNameSega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNK.
        /// </summary>
        internal static string ManufacturerNameSNK {
            get {
                return ResourceManager.GetString("ManufacturerNameSNK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sony.
        /// </summary>
        internal static string ManufacturerNameSony {
            get {
                return ResourceManager.GetString("ManufacturerNameSony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This archive contains no game file compatible with the selected system.
        /// </summary>
        internal static string NoCompatibleFileInArchiveAlertMessage {
            get {
                return ResourceManager.GetString("NoCompatibleFileInArchiveAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No compatible file found.
        /// </summary>
        internal static string NoCompatibleFileInArchiveAlertTitle {
            get {
                return ResourceManager.GetString("NoCompatibleFileInArchiveAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder you selected does not contain the game file you are trying to open. Try again..
        /// </summary>
        internal static string SelectFolderInvalidAlertMessage {
            get {
                return ResourceManager.GetString("SelectFolderInvalidAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid folder.
        /// </summary>
        internal static string SelectFolderInvalidAlertTitle {
            get {
                return ResourceManager.GetString("SelectFolderInvalidAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        internal static string SelectFolderRequestAlertAutomatic {
            get {
                return ResourceManager.GetString("SelectFolderRequestAlertAutomatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This game is made up of multiple files, do you want to load them? (if single file select &quot;No&quot;).
        /// </summary>
        internal static string SelectFolderRequestAlertMessage {
            get {
                return ResourceManager.GetString("SelectFolderRequestAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the game folder.
        /// </summary>
        internal static string SelectFolderRequestAlertTitle {
            get {
                return ResourceManager.GetString("SelectFolderRequestAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game saved to latest slot.
        /// </summary>
        internal static string StateSavedToAutoMessageBody {
            get {
                return ResourceManager.GetString("StateSavedToAutoMessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game state saved to slot {0}.
        /// </summary>
        internal static string StateSavedToSlotMessageBody {
            get {
                return ResourceManager.GetString("StateSavedToSlotMessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State saved.
        /// </summary>
        internal static string StateSavedToSlotMessageTitle {
            get {
                return ResourceManager.GetString("StateSavedToSlotMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3DO.
        /// </summary>
        internal static string System3DO {
            get {
                return ResourceManager.GetString("System3DO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anyone.
        /// </summary>
        internal static string SystemAnyCoreManfacture {
            get {
                return ResourceManager.GetString("SystemAnyCoreManfacture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Core.
        /// </summary>
        internal static string SystemAnyCoreName {
            get {
                return ResourceManager.GetString("SystemAnyCoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atari.
        /// </summary>
        internal static string SystemAtari {
            get {
                return ResourceManager.GetString("SystemAtari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atari 7800.
        /// </summary>
        internal static string SystemAtari7800 {
            get {
                return ResourceManager.GetString("SystemAtari7800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lynx.
        /// </summary>
        internal static string SystemAtariLynx {
            get {
                return ResourceManager.GetString("SystemAtariLynx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Boy Advance SP.
        /// </summary>
        internal static string SystemGameBoyAdvanceSP {
            get {
                return ResourceManager.GetString("SystemGameBoyAdvanceSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Boy Micro.
        /// </summary>
        internal static string SystemGameBoyMicro {
            get {
                return ResourceManager.GetString("SystemGameBoyMicro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCE.
        /// </summary>
        internal static string SystemGCEVectrex {
            get {
                return ResourceManager.GetString("SystemGCEVectrex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaguar.
        /// </summary>
        internal static string SystemJaguar {
            get {
                return ResourceManager.GetString("SystemJaguar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSX.
        /// </summary>
        internal static string SystemMSX {
            get {
                return ResourceManager.GetString("SystemMSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National.
        /// </summary>
        internal static string SystemMSXMan {
            get {
                return ResourceManager.GetString("SystemMSXMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32X.
        /// </summary>
        internal static string SystemName32X {
            get {
                return ResourceManager.GetString("SystemName32X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arcade.
        /// </summary>
        internal static string SystemNameArcade {
            get {
                return ResourceManager.GetString("SystemNameArcade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nintendo DS.
        /// </summary>
        internal static string SystemNameDS {
            get {
                return ResourceManager.GetString("SystemNameDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Boy.
        /// </summary>
        internal static string SystemNameGameBoy {
            get {
                return ResourceManager.GetString("SystemNameGameBoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Boy Advance.
        /// </summary>
        internal static string SystemNameGameBoyAdvance {
            get {
                return ResourceManager.GetString("SystemNameGameBoyAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Boy Color.
        /// </summary>
        internal static string SystemNameGameBoyColor {
            get {
                return ResourceManager.GetString("SystemNameGameBoyColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Gear.
        /// </summary>
        internal static string SystemNameGameGear {
            get {
                return ResourceManager.GetString("SystemNameGameGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master System.
        /// </summary>
        internal static string SystemNameMasterSystem {
            get {
                return ResourceManager.GetString("SystemNameMasterSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mega CD.
        /// </summary>
        internal static string SystemNameMegaCD {
            get {
                return ResourceManager.GetString("SystemNameMegaCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mega Drive.
        /// </summary>
        internal static string SystemNameMegaDrive {
            get {
                return ResourceManager.GetString("SystemNameMegaDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neo Geo.
        /// </summary>
        internal static string SystemNameNeoGeo {
            get {
                return ResourceManager.GetString("SystemNameNeoGeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neo Geo Pocket Color.
        /// </summary>
        internal static string SystemNameNeoGeoPocket {
            get {
                return ResourceManager.GetString("SystemNameNeoGeoPocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NES.
        /// </summary>
        internal static string SystemNameNES {
            get {
                return ResourceManager.GetString("SystemNameNES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NES (Nestopia).
        /// </summary>
        internal static string SystemNameNESNestopia {
            get {
                return ResourceManager.GetString("SystemNameNESNestopia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nintendo 64.
        /// </summary>
        internal static string SystemNameNintendo64 {
            get {
                return ResourceManager.GetString("SystemNameNintendo64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC Engine.
        /// </summary>
        internal static string SystemNamePCEngine {
            get {
                return ResourceManager.GetString("SystemNamePCEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC Engine CD.
        /// </summary>
        internal static string SystemNamePCEngineCD {
            get {
                return ResourceManager.GetString("SystemNamePCEngineCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC-FX.
        /// </summary>
        internal static string SystemNamePCFX {
            get {
                return ResourceManager.GetString("SystemNamePCFX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlayStation.
        /// </summary>
        internal static string SystemNamePlayStation {
            get {
                return ResourceManager.GetString("SystemNamePlayStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playstation Portable.
        /// </summary>
        internal static string SystemNamePlayStationPortable {
            get {
                return ResourceManager.GetString("SystemNamePlayStationPortable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PolyGame Master.
        /// </summary>
        internal static string SystemNamePolyGameMaster {
            get {
                return ResourceManager.GetString("SystemNamePolyGameMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturn.
        /// </summary>
        internal static string SystemNameSaturn {
            get {
                return ResourceManager.GetString("SystemNameSaturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SG-1000.
        /// </summary>
        internal static string SystemNameSG1000 {
            get {
                return ResourceManager.GetString("SystemNameSG1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Nintendo.
        /// </summary>
        internal static string SystemNameSNES {
            get {
                return ResourceManager.GetString("SystemNameSNES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WonderSwan Color.
        /// </summary>
        internal static string SystemNameWonderSwan {
            get {
                return ResourceManager.GetString("SystemNameWonderSwan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturn (Yabause).
        /// </summary>
        internal static string SystemSegaSaturnYabause {
            get {
                return ResourceManager.GetString("SystemSegaSaturnYabause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The 3DO Company.
        /// </summary>
        internal static string SystemThe3DOCompany {
            get {
                return ResourceManager.GetString("SystemThe3DOCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIOS files are required, Visit settings {0} page.
        /// </summary>
        internal static string SystemUnmetDependenciesAlertMessage {
            get {
                return ResourceManager.GetString("SystemUnmetDependenciesAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required files missing.
        /// </summary>
        internal static string SystemUnmetDependenciesAlertTitle {
            get {
                return ResourceManager.GetString("SystemUnmetDependenciesAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vectrex.
        /// </summary>
        internal static string SystemVectrex {
            get {
                return ResourceManager.GetString("SystemVectrex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Boy.
        /// </summary>
        internal static string SystemVirtualBoy {
            get {
                return ResourceManager.GetString("SystemVirtualBoy", resourceCulture);
            }
        }
    }
}
